In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   ----- ---------------------------------- 1.8/12.5 MB 15.2 MB/s eta 0:00:01
   ------------------ --------------------- 5.8/12.5 MB 17.3 MB/s eta 0:00:01
   ---------------------------- ----------- 8.9/12.5 MB 16.3 MB/s eta 0:00:01
   ---------------------------------------- 12.5/12.5 MB 17.1 MB/s  0:00:00



[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.4.6


In [ ]:
## 1. Creating arrays : 


In [4]:
list1 = [1,2, 3, 4]
print(list1)

[1, 2, 3, 4]


In [5]:
arr_list1 = np.array(list1)
print(arr_list1)

[1 2 3 4]


In [10]:
print(type(arr_list1))
print(arr_list1.ndim)

<class 'numpy.ndarray'>
1


In [11]:
list1 = [1,2,4]
list2 = [4,5,6]
arr_list1_2 = np.array([list1, list2])
print(arr_list1_2)
print(arr_list1_2.ndim)

[[1 2 4]
 [4 5 6]]
2


In [13]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
arr_list1_3 = np.array([[list1 , list2 , list3]])
print(arr_list1_3)
print(arr_list1_3.ndim)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [ ]:
## 2. numpy array attributes : 

In [15]:
arr1 = np.array([[1,2,3] , [4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [17]:
print("Shape :" , arr1.shape)
print("Size : " , arr1.size)
print("dType:" , arr1.dtype)
print("n_dim :" , arr1.ndim)

Shape : (2, 3)
Size :  6
dType: int64
n_dim : 2


In [23]:
# HW :  Create 2 array - 1D and 3D , and find it's attributes 

arr1 = np.array([1,2,3])
print(arr1)

print("Shape :" , arr1.shape)
print("Size : " , arr1.size)
print("dType:" , arr1.dtype)
print("n_dim :" , arr1.ndim)


print('-' * 50)

arr3 = np.array([[2,4,6] , [4,5,6] , [7,8,9]])
print(arr3)



print("Shape :" , arr3.shape)
print("Size : " , arr3.size)
print("dType:" , arr3.dtype)
print("n_dim :" , arr3.ndim)

[1 2 3]
Shape : (3,)
Size :  3
dType: int64
n_dim : 1
--------------------------------------------------
[[2 4 6]
 [4 5 6]
 [7 8 9]]
Shape : (3, 3)
Size :  9
dType: int64
n_dim : 2


In [ ]:
## 3. Array initialization methods : 

In [ ]:
#--> Zeros array :

In [25]:
zero_arr = np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#--> Ones array :

In [27]:
ones_arr = np.ones((1 , 4))
print(ones_arr)

[[1. 1. 1. 1.]]


In [ ]:
#--> Full array : 

In [28]:
full_arr = np.full((3,2),7)
print(full_arr)

[[7 7]
 [7 7]
 [7 7]]


In [ ]:
# Identity Matrix : 3 rows , 3 columns

In [29]:
id_arr = np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Empty array : 

In [30]:
print(np.empty(2))

[0. 0.]


In [ ]:
# evenly spaced array : 

In [32]:
print(np.arange(1, 10 ,2))

[1 3 5 7 9]


In [ ]:
# specific number of equally (spaced) values between a range : 

In [35]:
print(np.linspace(1 , 10 , 4))

[ 1.  4.  7. 10.]


In [ ]:
# random values array :   [float]

In [38]:
r_arr = np.random.rand(3,2)
print(r_arr)

[[0.79484037 0.31060892]
 [0.61778693 0.76758029]
 [0.87160928 0.24593445]]


In [ ]:
# random values array : [int]

In [39]:
rint_arr  = np.random.randint(1 , 100 , (3 ,3))
print(rint_arr)

[[15 64  7]
 [98  1  2]
 [15 62 60]]


In [ ]:
## 4. array Indexing and Slicing : 

In [40]:
a = np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [41]:
print(a[0])

1


In [42]:
print(a[-1])

9


In [43]:
#-->Slicing : 
#->array[start:stop:step]
#->stop - index , that is not included in output


In [ ]:
a = np.array([1,3,5,7,9])
print(a)

In [48]:
print(a[-3:])

[5 7 9]


In [ ]:
#--> Slicing : 2-D array