In [1]:
# BASICS OF NUMPY : 

# Creating Numpy Arrays :

In [3]:

# np.array :   [ 1D array ]   --> 'Vector' 

import numpy as np


a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
# np.array :   [ 2D array ]   --> 'Matrix'


import numpy as np


b = np.array([ [1,2,3], [4,5,6] ])
print(b)
print(type(b))


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [5]:
# np.array :   [ 3D array ]   --> 'Tensor'


import numpy as np


c = np.array([[[1,2], [3,4]],[[5,6] , [7,8]]])

print(c)
print(type(c))


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>


## dtype : 

In [6]:

# 1D array with float value : 

np.array([1,2,3] , dtype = float)


array([1., 2., 3.])

In [7]:
# 1D array with bool value :
np.array([1,2,3] , dtype = bool)

array([ True,  True,  True])

## np.arange :   

In [8]:
# it gives us tha facility to form the array with a given range. (same as range in python )
# syntax : np.arange(start , stop , step)

In [9]:
np.arange(1 , 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(1 ,11 ,2)

array([1, 3, 5, 7, 9])

In [11]:
# with reshape :

np.arange(1 , 11).reshape(2 ,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## np.ones and np.zeroes : 

In [12]:
# it provide us the matrix or array containing all ones or all zeroes as elements. 
# it is generally used to initialize the value of an array. 
# it also used to generate a array with random numbers. 

In [13]:
np.ones((3 ,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## np.random : 

In [15]:
# random numbers within 0 to 1 :

np.random.random((3 , 4))

array([[0.19068486, 0.26764288, 0.12942509, 0.2901256 ],
       [0.41353658, 0.49264417, 0.26044604, 0.10841991],
       [0.83744135, 0.86378379, 0.68666109, 0.64088423]])

## np.linspace :

In [16]:
# ye linearly seperable points generate krta hai in a given range. 
# ml algorithm ka result dekhne ke kaam aata h. 

In [17]:
np.linspace(-10 , 10 , 10)


array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

## np.identity :


In [18]:
# provide the identity matrix.

In [19]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Array Attributes : 

## np.arange :

In [20]:
a1 = np.arange(10)    #--> 1D array [ vector ] 
a2 = np.arange(12 , dtype = float).reshape(3 , 4)    #--> 2D array [ Matrix ] 
a3 = np.arange(8).reshape(2,2,2)     #--> 3D array [ Tensor ] 

In [21]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [23]:
a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

## ndim : 

In [24]:
# gives us the dimension of given array. 
# syntax : array_name.ndim

In [25]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)


1
2
3


## shape :

In [26]:
# it gives us the info about rows and columns in an array.

In [27]:
print(a1.shape)



(10,)


In [28]:
print(a2.shape)

(3, 4)


In [29]:
print(a3.shape)

(2, 2, 2)


## size :


In [30]:
# total number of elements return krta hai array ke ander ke.

In [31]:
a1.size

10

In [32]:
a2.size

12

In [33]:
a3.size

8

## itemsize

In [34]:
# integer 64 bit mai kitni byte le rha hai voh batata hai.

In [35]:
a1.itemsize

8

In [36]:
a2.itemsize

8

In [37]:
a3.itemsize


8

## dtype :

In [38]:
# items ka data type batata hai.

In [39]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


# Changing data type :

In [40]:
# changes the data type of array. 

## astype :


In [41]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operations :

In [42]:
# creating array : 

a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12 ,24).reshape(3,4)

In [43]:
a1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Scaler Operartions : 

In [45]:
# arithmetic :

a1 + 2
a1 * 2 
a1 - 2 
a1 // 2

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5]])

In [46]:
# relational : 

a1 <= 15 
a2 >= 5

a1 > 4
a2 < 5


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

## Vector Opperations :

In [47]:
# arithmetic : 

a1 + a2 
a1 * a2 
a1 - a2 
a1 / a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [48]:
# relational : 

a1 <= 15 
a2 >= 5

a1 > 4
a2 < 5


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

# Array Functions : 


In [49]:
# creating array : 

a1 = np.random.random((3,3))
a1 = np.round(a1 * 100 )


In [50]:
a1

array([[46., 61., 88.],
       [10., 90., 45.],
       [88., 81., 90.]])

## max/min/sum/prod :

In [51]:
# max :

np.max(a1)




np.float64(90.0)

In [52]:
# min :

np.min(a1)

np.float64(10.0)

In [53]:
# sum :

np.sum(a1)

np.float64(599.0)

In [54]:
# prod : 

np.prod(a1)

np.float64(6415574647680000.0)

In [55]:
# har row/column ka minimun/maximum value  : 

# axis =  0 --> column ,
# axis =  1 --> row.





In [56]:
np.max(a1 , axis = 0)  #--> column wise max value .

array([88., 90., 90.])

In [57]:
np.max(a1 , axis = 1)  #--> row wise max value .


array([88., 90., 90.])

## mean / meadian / std / var  :


In [58]:
# mean : 

np.mean(a1 , axis = 1)
np.mean(a1 , axis = 0)

array([48.        , 77.33333333, 74.33333333])

In [59]:
# median : 

np.median(a1 , axis = 1)
np.median(a1 , axis = 0)

array([46., 81., 88.])

In [60]:
# standard deviation :

np.std(a1 , axis = 1)
np.std(a1 , axis = 0)

array([31.8747549 , 12.11977264, 20.7578633 ])

In [61]:
# variance : 

np.var(a1 , axis = 1)
np.var(a1 , axis = 0)


array([1016.        ,  146.88888889,  430.88888889])

## Trigonometric Functions :

In [62]:
np.sin(a1)

array([[ 0.90178835, -0.96611777,  0.0353983 ],
       [-0.54402111,  0.89399666,  0.85090352],
       [ 0.0353983 , -0.62988799,  0.89399666]])

## dot product : 

In [63]:
# pahle wale matrix ka column  , dusre wale matrix ke row se match karna chaiye. 

In [64]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12 , 24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

## log and exponents : 



In [65]:
np.exp(a1)

array([[9.49611942e+19, 3.10429794e+26, 1.65163625e+38],
       [2.20264658e+04, 1.22040329e+39, 3.49342711e+19],
       [1.65163625e+38, 1.50609731e+35, 1.22040329e+39]])

## round / floor / ceil : 

In [66]:
np.random.random((2,3)) * 100

array([[ 2.10896331, 22.38657356, 38.71776161],
       [77.47401259, 43.46510082, 75.94416114]])

In [67]:
# round : 

np.round(np.random.random((2,3)) * 100) 


array([[13., 92., 98.],
       [49., 18., 59.]])

In [68]:
# floor : 

np.floor(np.random.random((2,3)) * 100) 

array([[83.,  5., 85.],
       [93., 71., 10.]])

In [69]:
# ceil : 

np.ceil(np.random.random((2,3)) * 100) 

array([[98., 13., 29.],
       [24., 66., 20.]])

# Indexing and Slicing :

## indexing:


In [70]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [71]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
a1[-1]
a1[2]

np.int64(2)

In [72]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# rows :-->    0 , 1 , 2.
# columns :--> 0 , 1 , 2 ,3.

#--> indexing :  [rows , columns] 

In [78]:
a2[1,1]

np.int64(5)

In [73]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# rows :--> 0 , 1 .

# 0  :  
# --> rows : 0 , 1.
# --> cols : 0 , 1.


# 1  :  
# --> rows : 0 , 1.
# --> cols : 0 , 1.


In [79]:
#finding 5 : 

a3[1 , 0 , 1]

np.int64(5)

In [80]:
#finding 2 : 

a3[0 , 1 , 0]

np.int64(2)

## Slicing : 


In [81]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [85]:
a1[2:7]

array([2, 3, 4, 5, 6])

In [88]:
a1[2:8:2]


array([2, 4, 6])

In [ ]:
## 2d array slicing :

In [89]:


a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:

# 1st row : 
a2[0,:]

# 2nd row :
a2[1,:]

# 3rd row : 
a2[2,:]

array([ 8,  9, 10, 11])

In [102]:
# 1st column :
#a2[:,0]


# 2nd column :
#a2[:,1]


# 3rd column :
a2[:,2]

# 4th column :
a2[:,3]

array([ 3,  7, 11])

In [ ]:
# finding subset of 2d array : 
# arr[rows,cols]

# [ 5 , 6
#  9 ,10 ]

In [103]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
# finding subset of 2d array : 
# arr[rows,cols]

# [ 0 , 3
#   8 , 11 ]

In [104]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
# finding subset of 2d array : 
# arr[rows,cols]

# [ 1 , 3
#   9 , 11 ]

In [106]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [107]:
# finding subset of 2d array : 
# arr[rows,cols]

# [ 4 , 7 ]

In [136]:
a2[1::2, ::3]


array([[4, 7]])

In [ ]:
# finding subset of 2d array : 
# arr[rows,cols]

# [ 1 , 2 , 3
#   5 , 6 , 7 ]

In [137]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [140]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
## 3d array slicing :

# array[ matrix_number , row , column ]

In [143]:
a3 = np.arange(27).reshape(3,3,3)

a3


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [144]:
a3[0 , 1 , :]


array([3, 4, 5])

In [146]:
a3[1 , : , 1::3]



array([[10],
       [13],
       [16]])

In [147]:
a3[2 , 1: ,1::]


array([[22, 23],
       [25, 26]])

In [152]:
a3[::2 , 0::3 , ::2 ]



array([[[ 0,  2]],

       [[18, 20]]])

#  Iterating : 

In [154]:
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [155]:
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [156]:
for i in a1:
    print(i)
    

0
1
2
3
4
5
6
7
8
9


In [157]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [158]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [159]:
# iteration to find 3D array as linear array : 

for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping : 

## reshape : 


In [162]:
# array ko defined shape(row , col) mai convert krta hai . 


In [171]:
a1 = np.arange(8)
a1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [175]:
a2 = np.arange(12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Transpose : 

In [176]:
# syntax : 1

np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [178]:
# syntax : 2


a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## ravel : 


In [179]:
# kisi bhi dimension ke array ko 1D array mai convert krta hai. 

In [182]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [181]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking : 

## horizontal stacking :


In [184]:
a4 = np.arange(12).reshape(3,4)

a5 = np.arange(12 , 24).reshape(3,4)

In [185]:
a4



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [186]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [187]:
# horizontal stacking : 

np.hstack((a4 , a5))


array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

## Vertical Stacking : 

In [189]:
a6 = np.arange(12).reshape(3,4)

a7 = np.arange(12 , 24).reshape(3,4)

In [190]:
np.vstack((a6 , a7))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Spliting : 

## Horizontal Splitting : 

In [191]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [193]:
np.hsplit(a4 , 2)


[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

## Vertical Splitting : 

In [199]:
a5  = np.arange(16).reshape(4,4)



In [201]:
a5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [202]:
np.vsplit(a5 , 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]