# Creating Numpy Arrays :

In [3]:

# np.array :   [ 1D array ]   --> 'Vector' 

import numpy as np


a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
# np.array :   [ 2D array ]   --> 'Matrix'


import numpy as np


b = np.array([ [1,2,3], [4,5,6] ])
print(b)
print(type(b))


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [6]:
# np.array :   [ 3D array ]   --> 'Tensor'


import numpy as np


c = np.array([[[1,2], [3,4]],[[5,6] , [7,8]]])

print(c)
print(type(c))


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>


## dtype : 

In [9]:

# 1D array with float value : 

np.array([1,2,3] , dtype = float)


array([1., 2., 3.])

In [11]:
# 1D array with bool value :
np.array([1,2,3] , dtype = bool)

array([ True,  True,  True])

## np.arange :   

In [12]:
# it gives us tha facility to form the array with a given range. (same as range in python )
# syntax : np.arange(start , stop , step)

In [13]:
np.arange(1 , 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(1 ,11 ,2)

array([1, 3, 5, 7, 9])

In [16]:
# with reshape :

np.arange(1 , 11).reshape(2 ,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## np.ones and np.zeroes : 

In [17]:
# it provide us the matrix or array containing all ones or all zeroes as elements. 
# it is generally used to initialize the value of an array. 
# it also used to generate a array with random numbers. 

In [18]:
np.ones((3 ,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## np.random : 

In [22]:
# random numbers within 0 to 1 :

np.random.random((3 , 4))

array([[0.66072583, 0.34104097, 0.72886286, 0.15660469],
       [0.32118291, 0.58033427, 0.50023958, 0.42025146],
       [0.91705752, 0.73505024, 0.6809082 , 0.58685785]])

## np.linspace :

In [24]:
# ye linearly seperable points generate krta hai in a given range. 
# ml algorithm ka result dekhne ke kaam aata h. 

In [25]:
np.linspace(-10 , 10 , 10)


array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

## np.identity :


In [ ]:
# provide the identity matrix.

In [27]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Array Attributes : 

In [28]:
a1 = np.arange(10)    #--> 1D array [ vector ] 
a2 = np.arange(12 , dtype = float).reshape(3 , 4)
a3 = np.arange(8).reshape(2,2,2)

In [35]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [37]:
a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

## ndim : 

In [ ]:
# gives us the dimension of given array 
# syntax : array_name.ndim

In [31]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)


1
2
3


## shape :

In [32]:
# it gives us the info about rows and columns in an array.

In [38]:
print(a1.shape)



(10,)


In [39]:
print(a2.shape)

(3, 4)


In [40]:
print(a3.shape)

(2, 2, 2)


## size :


In [ ]:
# total number of elements return krta hai array ke ander ke.

In [41]:
a1.size

10

In [42]:
a2.size

12

In [43]:
a3.size

8

## itemsize

In [ ]:
# integer 64 bit mai kitni byte le rha hai voh batata hai.

In [44]:
a1.itemsize

8

In [45]:
a2.itemsize

8

In [46]:
a3.itemsize


8

## dtype :

In [ ]:
# items ka data type batata hai

In [47]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


# Changing data type :

In [ ]:
# changes the data type of array. 

## astype :


In [48]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operations :