
# Numpy Tricks : 

In [7]:
import numpy as np 
a = np.random.randint(1,100,15)

b = np.random.randint(1,100,24).reshape(6,4)

In [8]:
a

array([76, 46, 62, 94, 83, 43, 91, 53, 17, 31, 70, 57, 37, 54, 82],
      dtype=int32)

In [9]:
b

array([[55, 75, 15, 44],
       [90, 22, 26,  1],
       [94,  4, 87, 63],
       [89, 62, 36, 52],
       [30, 64, 18, 44],
       [99, 30, 81, 74]], dtype=int32)

## np.sort

In [3]:
# Returns a sorted of an array.

# documentation : https://numpy.org/doc/stable/reference/generated/numpy.sort.html


In [ ]:
# syntax : np.sort(array_name , axis , kind , order)

 ### Ascending : 




In [15]:
np.sort(a)

array([17, 31, 37, 43, 46, 53, 54, 57, 62, 70, 76, 82, 83, 91, 94],
      dtype=int32)

In [12]:



np.sort(b)  #--> row wise sort

np.sort(b , axis = 0)  #--> column wise sort

array([[30,  4, 15,  1],
       [55, 22, 18, 44],
       [89, 30, 26, 44],
       [90, 62, 36, 52],
       [94, 64, 81, 63],
       [99, 75, 87, 74]], dtype=int32)

### descending :



In [16]:
np.sort(a)[::-1]

array([94, 91, 83, 82, 76, 70, 62, 57, 54, 53, 46, 43, 37, 31, 17],
      dtype=int32)

In [17]:



np.sort(b)[::-1]  #--> row wise sort

np.sort(b , axis = 0)[::-1]  #--> column wise sort

array([[99, 75, 87, 74],
       [94, 64, 81, 63],
       [90, 62, 36, 52],
       [89, 30, 26, 44],
       [55, 22, 18, 44],
       [30,  4, 15,  1]], dtype=int32)

## np.append : 

In [18]:
# The numpy.append() appends values along the mentioned axis at the end of the array.

# Documentation : https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [19]:
# code : 

np.append(a , 200)

array([ 76,  46,  62,  94,  83,  43,  91,  53,  17,  31,  70,  57,  37,
        54,  82, 200])

### Appending an column at the end : 



In [32]:
np.append(b , np.ones((b.shape[0],1)) , axis = 1)

array([[55., 75., 15., 44.,  1.],
       [90., 22., 26.,  1.,  1.],
       [94.,  4., 87., 63.,  1.],
       [89., 62., 36., 52.,  1.],
       [30., 64., 18., 44.,  1.],
       [99., 30., 81., 74.,  1.]])

### Appending an row at the end : 

In [34]:
np.append(b, np.ones((1, b.shape[1])), axis=0)

array([[55., 75., 15., 44.],
       [90., 22., 26.,  1.],
       [94.,  4., 87., 63.],
       [89., 62., 36., 52.],
       [30., 64., 18., 44.],
       [99., 30., 81., 74.],
       [ 1.,  1.,  1.,  1.]])

## np.concatenate : 

In [35]:

# numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

# documentation : https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [37]:
# code : 

c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print('-' * 50)
print(d)

[[0 1 2]
 [3 4 5]]
--------------------------------------------------
[[ 6  7  8]
 [ 9 10 11]]


### Row-wise concatenate : 

In [39]:
np.concatenate((c,d) , axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### Column-wise concatenate : 


In [41]:
np.concatenate((c,d) , axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## np.unique : 

In [42]:

# With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

# Documentation : https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [43]:
# code : 

e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [44]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

## np.expand_dims : 

In [46]:

# With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array. [1D ko 2D and 2D ko 3D mai convert karna]. 

# Documentation :  https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [47]:
a.shape


(15,)

### 1D array ko 2D main convert karna : [ row vector ]



In [53]:

np.expand_dims(a , axis = 0)

array([[76, 46, 62, 94, 83, 43, 91, 53, 17, 31, 70, 57, 37, 54, 82]],
      dtype=int32)

In [50]:
np.expand_dims(a , axis = 0).shape


(1, 15)

### 1D array ko 2D main convert karna : [ column vector ]



In [54]:

np.expand_dims(a , axis = 1)

array([[76],
       [46],
       [62],
       [94],
       [83],
       [43],
       [91],
       [53],
       [17],
       [31],
       [70],
       [57],
       [37],
       [54],
       [82]], dtype=int32)

## np.where : 

In [55]:

# The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

# Documentation : https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
# syntax :  np.where(condition , true , false) [ agar condition true hai toh true wala chlega , otherwise false wala chlega ].

In [56]:
a

array([76, 46, 62, 94, 83, 43, 91, 53, 17, 31, 70, 57, 37, 54, 82],
      dtype=int32)

In [57]:
# find all indices with value greater than 50 : 

np.where(a > 50 )

(array([ 0,  2,  3,  4,  6,  7, 10, 11, 13, 14]),)

In [58]:
# replace all values > 50 with 0 :

np.where(a > 50 , 0, a)

array([ 0, 46,  0,  0,  0, 43,  0,  0, 17, 31,  0,  0, 37,  0,  0],
      dtype=int32)

## np.argmax / np.argmin : 




In [59]:

# The numpy.argmax()/numpy.argmin function returns indices of the max/min element of the array in a particular axis.

# Documentatiton : https://numpy.org/doc/stable/reference/generated/numpy.argmax.html


### np.argmax

In [60]:
a

array([76, 46, 62, 94, 83, 43, 91, 53, 17, 31, 70, 57, 37, 54, 82],
      dtype=int32)

In [62]:
np.argmax(a)  #--> max element ka index return krega.

np.int64(3)

In [61]:
b 

array([[55, 75, 15, 44],
       [90, 22, 26,  1],
       [94,  4, 87, 63],
       [89, 62, 36, 52],
       [30, 64, 18, 44],
       [99, 30, 81, 74]], dtype=int32)

In [63]:
np.argmax(b , axis = 0)  #--> return indexes of max element in the column.

array([5, 0, 2, 5])

In [64]:
np.argmax(b , axis = 1)  #--> return indexes of max element in the row.

array([1, 0, 0, 0, 1, 0])

### np.argmin : 

In [65]:
a


array([76, 46, 62, 94, 83, 43, 91, 53, 17, 31, 70, 57, 37, 54, 82],
      dtype=int32)

In [66]:
np.argmin(a)  #--> min element ka index return krega.

np.int64(8)

In [67]:
b

array([[55, 75, 15, 44],
       [90, 22, 26,  1],
       [94,  4, 87, 63],
       [89, 62, 36, 52],
       [30, 64, 18, 44],
       [99, 30, 81, 74]], dtype=int32)

In [68]:
np.argmin(b , axis = 0)  #--> return indexes of min element in the column.

array([4, 2, 0, 1])

In [69]:
np.argmin(b , axis = 1)  #--> return indexes of min element in the row.

array([2, 3, 1, 2, 2, 1])

## np.cumsum : 

In [70]:

# numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

# Documentation : https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [71]:
a

array([76, 46, 62, 94, 83, 43, 91, 53, 17, 31, 70, 57, 37, 54, 82],
      dtype=int32)

In [72]:
np.cumsum(a)


array([ 76, 122, 184, 278, 361, 404, 495, 548, 565, 596, 666, 723, 760,
       814, 896])

In [73]:
b


array([[55, 75, 15, 44],
       [90, 22, 26,  1],
       [94,  4, 87, 63],
       [89, 62, 36, 52],
       [30, 64, 18, 44],
       [99, 30, 81, 74]], dtype=int32)

In [74]:
# without axis :

np.cumsum(b)


array([  55,  130,  145,  189,  279,  301,  327,  328,  422,  426,  513,
        576,  665,  727,  763,  815,  845,  909,  927,  971, 1070, 1100,
       1181, 1255])

In [77]:
# With axis :  column

np.cumsum(b , axis = 0)



array([[ 55,  75,  15,  44],
       [145,  97,  41,  45],
       [239, 101, 128, 108],
       [328, 163, 164, 160],
       [358, 227, 182, 204],
       [457, 257, 263, 278]])

In [76]:
# With axis : row

np.cumsum(b , axis = 1)


array([[ 55, 130, 145, 189],
       [ 90, 112, 138, 139],
       [ 94,  98, 185, 248],
       [ 89, 151, 187, 239],
       [ 30,  94, 112, 156],
       [ 99, 129, 210, 284]])

In [78]:
# NOTE : 

#--> np.cumprod : 

np.cumprod(a)


array([                  76,                 3496,               216752,
                   20374688,           1691099104,          72717261472,
              6617270793952,      350715352079456,     5962160985350752,
         184826990545873312, -5508854735498419776,  -410070670347549760,
        3274129270850210496, -7664460111184149376, -1296430610975493888])

## np.percentile : 

In [81]:
# numpy.percentile() function used to compute the nth percentile of the given data (array elements) along the specified axis. 

# Documentation : https://numpy.org/doc/stable/reference/generated/numpy.percentile.html


In [82]:
a

array([76, 46, 62, 94, 83, 43, 91, 53, 17, 31, 70, 57, 37, 54, 82],
      dtype=int32)

In [83]:
np.percentile(a, 100)  #--> returns the max value.

np.float64(94.0)

In [84]:
np.percentile(a ,50) 


np.float64(57.0)

In [85]:
np.median(a)

np.float64(57.0)

## np.histogram : 
