# Creating Numpy Arrays :

In [2]:

# np.array :   [ 1D array ]   --> 'Vector' 

import numpy as np


a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
# np.array :   [ 2D array ]   --> 'Matrix'


import numpy as np


b = np.array([ [1,2,3], [4,5,6] ])
print(b)
print(type(b))


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [4]:
# np.array :   [ 3D array ]   --> 'Tensor'


import numpy as np


c = np.array([[[1,2], [3,4]],[[5,6] , [7,8]]])

print(c)
print(type(c))


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>


## dtype : 

In [5]:

# 1D array with float value : 

np.array([1,2,3] , dtype = float)


array([1., 2., 3.])

In [6]:
# 1D array with bool value :
np.array([1,2,3] , dtype = bool)

array([ True,  True,  True])

## np.arange :   

In [7]:
# it gives us tha facility to form the array with a given range. (same as range in python )
# syntax : np.arange(start , stop , step)

In [8]:
np.arange(1 , 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(1 ,11 ,2)

array([1, 3, 5, 7, 9])

In [10]:
# with reshape :

np.arange(1 , 11).reshape(2 ,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## np.ones and np.zeroes : 

In [11]:
# it provide us the matrix or array containing all ones or all zeroes as elements. 
# it is generally used to initialize the value of an array. 
# it also used to generate a array with random numbers. 

In [12]:
np.ones((3 ,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## np.random : 

In [14]:
# random numbers within 0 to 1 :

np.random.random((3 , 4))

array([[0.39329973, 0.60935499, 0.69881388, 0.04470626],
       [0.81432137, 0.13834792, 0.31659125, 0.83224638],
       [0.67708597, 0.67229894, 0.02456613, 0.20537052]])

## np.linspace :

In [15]:
# ye linearly seperable points generate krta hai in a given range. 
# ml algorithm ka result dekhne ke kaam aata h. 

In [16]:
np.linspace(-10 , 10 , 10)


array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

## np.identity :


In [17]:
# provide the identity matrix.

In [18]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Array Attributes : 

## np.arange :

In [19]:
a1 = np.arange(10)    #--> 1D array [ vector ] 
a2 = np.arange(12 , dtype = float).reshape(3 , 4)    #--> 2D array [ Matrix ] 
a3 = np.arange(8).reshape(2,2,2)     #--> 3D array [ Tensor ] 

In [35]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [37]:
a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

## ndim : 

In [ ]:
# gives us the dimension of given array. 
# syntax : array_name.ndim

In [31]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)


1
2
3


## shape :

In [32]:
# it gives us the info about rows and columns in an array.

In [38]:
print(a1.shape)



(10,)


In [39]:
print(a2.shape)

(3, 4)


In [40]:
print(a3.shape)

(2, 2, 2)


## size :


In [ ]:
# total number of elements return krta hai array ke ander ke.

In [41]:
a1.size

10

In [42]:
a2.size

12

In [43]:
a3.size

8

## itemsize

In [ ]:
# integer 64 bit mai kitni byte le rha hai voh batata hai.

In [44]:
a1.itemsize

8

In [45]:
a2.itemsize

8

In [46]:
a3.itemsize


8

## dtype :

In [ ]:
# items ka data type batata hai.

In [47]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


# Changing data type :

In [ ]:
# changes the data type of array. 

## astype :


In [48]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operations :

In [21]:
# creating array : 

a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12 ,24).reshape(3,4)

In [23]:
a1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Scaler Operartions : 

In [26]:
# arithmetic :

a1 + 2
a1 * 2 
a1 - 2 
a1 // 2

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5]])

In [29]:
# relational : 

a1 <= 15 
a2 >= 5

a1 > 4
a2 < 5


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

## Vector Opperations :

In [30]:
# arithmetic : 

a1 + a2 
a1 * a2 
a1 - a2 
a1 / a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [31]:
# relational : 

a1 <= 15 
a2 >= 5

a1 > 4
a2 < 5


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

# Array Functions : 


In [38]:
# creating array : 

a1 = np.random.random((3,3))
a1 = np.round(a1 * 100 )


In [39]:
a1

array([[ 2., 54., 98.],
       [11., 89., 46.],
       [35., 58., 40.]])

## max/min/sum/prod :

In [40]:
# max :

np.max(a1)




np.float64(98.0)

In [42]:
# min :

np.min(a1)

np.float64(2.0)

In [43]:
# sum :

np.sum(a1)

np.float64(433.0)

In [44]:
# prod : 

np.prod(a1)

np.float64(38703156307200.0)

In [50]:
# har row/column ka minimun/maximum value  : 

# axis =  0 --> column ,
# axis =  1 --> row.





In [47]:
np.max(a1 , axis = 0)  #--> column wise max value .

array([35., 89., 98.])

In [46]:
np.max(a1 , axis = 1)  #--> row wise max value .


array([98., 89., 58.])

## mean / meadian / std / var  :


In [55]:
# mean : 

np.mean(a1 , axis = 1)
np.mean(a1 , axis = 0)

array([16.        , 67.        , 61.33333333])

In [56]:
# median : 

np.median(a1 , axis = 1)
np.median(a1 , axis = 0)

array([11., 58., 46.])

In [57]:
# standard deviation :

np.std(a1 , axis = 1)
np.std(a1 , axis = 0)

array([13.92838828, 15.64182428, 26.04269998])

In [58]:
# variance : 

np.var(a1 , axis = 1)
np.var(a1 , axis = 0)


array([194.        , 244.66666667, 678.22222222])

## Trigonometric Functions :

In [60]:
np.sin(a1)

array([[ 0.90929743, -0.55878905, -0.57338187],
       [-0.99999021,  0.86006941,  0.90178835],
       [-0.42818267,  0.99287265,  0.74511316]])

## dot product : 

In [ ]:
# pahle wale matrix ka column  , dusre wale matrix ke row se match karna chaiye. 

In [61]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12 , 24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

## log and exponents : 



In [62]:
np.exp(a1)

array([[7.38905610e+00, 2.83075330e+23, 3.63797095e+42],
       [5.98741417e+04, 4.48961282e+38, 9.49611942e+19],
       [1.58601345e+15, 1.54553894e+25, 2.35385267e+17]])

## round / floor / ceil : 

In [66]:
np.random.random((2,3)) * 100

array([[77.85054713, 61.7850061 , 10.07355096],
       [41.10701395, 59.64436021, 16.89128059]])

In [67]:
# round : 

np.round(np.random.random((2,3)) * 100) 


array([[10., 19., 57.],
       [65., 85., 15.]])

In [69]:
# floor : 

np.floor(np.random.random((2,3)) * 100) 

array([[86., 86., 58.],
       [90.,  2., 15.]])

In [70]:
# ceil : 

np.ceil(np.random.random((2,3)) * 100) 

array([[29., 16., 75.],
       [ 9., 36., 47.]])