In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
a
type(a)

numpy.ndarray

In [4]:
b = np.array([ [1,2,3] , [4,5,6] ])
b

b.ndim

2

In [5]:
c = np.array([ [1,2,3] , [4,5,6] , [7,8,9] ])
c

c.ndim

2

In [6]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
d = np.array( [ [ [1,2] , [3,4] ] , [ [5,6] , [7,8] ] ] )
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [8]:
np.array([1,2,3] , dtype = 'float')

array([1., 2., 3.])

In [9]:
np.array([1,2,3,4], dtype = 'bool')


array([ True,  True,  True,  True])

In [10]:
# 1d :

import numpy as np
a = np.array([1,2,3])
print(a)
print(type(a))
print(a.ndim)

# 2d : 

import numpy as np
b = np.array( [ [1,2,4] , [5,6,7] ] )
print(b)
print(type(b))
print(b.ndim)



# 3d : 

import numpy as np
c = np.array( [ [ [1,2,4] , [5,6,7] ]  , [ [8,9,10] , [11,12,14] ] ] )
print(c)
print(type(c))
print(c.ndim)

[1 2 3]
<class 'numpy.ndarray'>
1
[[1 2 4]
 [5 6 7]]
<class 'numpy.ndarray'>
2
[[[ 1  2  4]
  [ 5  6  7]]

 [[ 8  9 10]
  [11 12 14]]]
<class 'numpy.ndarray'>
3


In [11]:
## array attribute : 

# np.arange :-

a = np.arange(12)    #--> [ 1D array - [vector] ]
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)
print(a.itemsize)
print(a.dtype)
print(a.astype(np.int32))

print('-' * 50 )

a = np.arange(16).reshape(4,4)    #--> [ 2D array - [matrix] ]
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)
print(a.itemsize)
print(a.dtype)
print(a.astype(np.int32))

print('-' * 50 )

a = np.arange(18).reshape(3,2,3)    #--> [ 3D array - [tensor] ]
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)
print(a.itemsize)
print(a.dtype)
print(a.astype(np.int32))



[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>
1
(12,)
12
8
int64
[ 0  1  2  3  4  5  6  7  8  9 10 11]
--------------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
<class 'numpy.ndarray'>
2
(4, 4)
16
8
int64
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
--------------------------------------------------
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
<class 'numpy.ndarray'>
3
(3, 2, 3)
18
8
int64
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [12]:
## Array Operations : 
import numpy as np

a = np.arange(12).reshape(3,4)

b = np.arange(12,24).reshape(3,4)



In [13]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [15]:
#:--> Scalar operation : 

#--> arithmetic : 

a * 2
a + 2
a - 2
a // 2


#--> relational : 

a > 2
a < 2
a >= 4
a <= 4
a != 5


array([[ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [16]:
#:--> Vector Operations : 

In [17]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [19]:
a + b
a - b
a * b
a // b


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [20]:
a <= 5 
b >= 2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [21]:
# --> array Functions :

In [22]:
a = np.random.random((3,4))
a = np.round(a*100)
a

array([[39.,  1.,  7., 58.],
       [87.,  0., 92., 66.],
       [58., 19.,  4., 26.]])

In [23]:
print(a.max())
print(a.min())
print(a.mean())
print(a.std())
print(a.sum())
print(a.prod())
print(a.var())
print(np.median(a , axis = 1))
print(np.median(b , axis = 0))

92.0
0.0
38.083333333333336
32.0636303136262
457.0
0.0
1028.076388888889
[23.  76.5 22.5]
[16. 17. 18. 19.]


In [24]:
a = np.arange(12).reshape(3,4)
b = np.arange(12 , 24).reshape(4,3)


In [25]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
b

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [27]:
np.dot(a,b)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [28]:
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [29]:
## round / floor / ceil : 

a = np.random.random((3,4)) * 100
a

array([[65.42374311, 88.40252437, 59.74079065, 68.61809768],
       [90.190873  , 38.97295918, 38.04444812, 32.45030273],
       [95.0871146 , 13.93626352, 61.81074412, 74.71742994]])

In [33]:
## round / floor / ceil : 

a.round()
np.floor(a)
np.ceil(a)

array([[66., 89., 60., 69.],
       [91., 39., 39., 33.],
       [96., 14., 62., 75.]])

In [34]:
## indexing and slicing : 


In [37]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
for i in a:  
    print(a[i])



    
        



0
1
2
3
4
5
6
7
8
9


In [45]:
a[-1]
a[2]
a[-2]

np.int64(8)

In [59]:
a[0:5]

array([0, 1, 2, 3, 4])

In [39]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
b[2, 0]


np.int64(8)

In [93]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
for i in b:
    print(i)

    

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [74]:
b[0]  #--> 1st row
b[1]  #--> 2nd row
b[2]  #--> 3rd row



# b[:,0]  #--> 1st col
# b[:,1]  #--> 2nd col
# b[:,2]  #--> 3rd col
# b[:,3]  #--> 4th col




array([ 8,  9, 10, 11])

In [77]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
b[ 0:3 , 2:4 ]




array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [42]:
c = np.arange(16).reshape(2,2,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [97]:
for i in np.nditer(c):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [58]:
c[0]
c[1]

c[0][1][2]

np.int64(6)

In [82]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [85]:
c[ 1 , 0:2 , 1:3]

array([[ 9, 10],
       [13, 14]])

In [98]:
## stacking :


a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
b = np.arange(12 , 24).reshape(3,4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [102]:
## hstack and vstack : 

np.hstack((a,b))
np.vstack((a,b))



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [105]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [111]:
## splitting : 

np.hsplit(a , 2)
c = np.arange(8).reshape(4,2)
np.vsplit(c , 2)

[array([[0, 1],
        [2, 3]]),
 array([[4, 5],
        [6, 7]])]

In [125]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
## Fancing Indexing : 

a[ [0 , 1, 2] ]  #--> all rows

a[ : ,  [0 , 1 ,2 ,3] ]  #--> all columns

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [143]:
a[ [0 , 1] ]   ##--> 1st and 2nd row

a[ [1, 2] ]  ##--> 2nd and 3rd row

a[ : , [0 , 1] ]  ##--> 1st and 2nd col  

a[ : , [1,2] ] ##--> 2nd and 3rd col

a[ : , [2,3] ] ##--> 3rd and 4th col

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [147]:
## boolean indexing : 

a = np.random.randint(1 , 100 , 24).reshape(6 , 4)
a

array([[ 8, 65, 84, 14],
       [88, 33, 15, 41],
       [37, 52, 33, 80],
       [13, 26, 56, 94],
       [11, 70, 34,  8],
       [46, 70,  9, 99]], dtype=int32)

In [156]:
a > 50
a < 50

a >= 50
a[a <= 50].reshape(7,2)




array([[ 8, 14],
       [33, 15],
       [41, 37],
       [33, 13],
       [26, 11],
       [34,  8],
       [46,  9]], dtype=int32)

In [160]:
a[a % 2 == 0].reshape(7 , 2)

array([[ 8, 84],
       [14, 88],
       [52, 80],
       [26, 56],
       [94, 70],
       [34,  8],
       [46, 70]], dtype=int32)

In [165]:
a[(a % 2 == 0) & (a > 50)].reshape(4,2)

array([[84, 88],
       [52, 80],
       [56, 94],
       [70, 70]], dtype=int32)

In [167]:
a[a % 7 == 0]

array([84, 14, 56, 70, 70], dtype=int32)

In [168]:
## Broadcasting : 

a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [169]:
b = np.arange(6 ,12).reshape(2,3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [170]:
a + b

array([[ 6,  8, 10],
       [12, 14, 16]])

In [172]:
abs(a  - b)

array([[6, 6, 6],
       [6, 6, 6]])