In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
a
type(a)

numpy.ndarray

In [8]:
b = np.array([ [1,2,3] , [4,5,6] ])
b

b.ndim

2

In [12]:
c = np.array([ [1,2,3] , [4,5,6] , [7,8,9] ])
c

c.ndim

2

In [13]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
d = np.array( [ [ [1,2] , [3,4] ] , [ [5,6] , [7,8] ] ] )
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

dtype('int64')

In [17]:
np.array([1,2,3] , dtype = 'float')

array([1., 2., 3.])

In [18]:
np.array([1,2,3,4], dtype = 'bool')


array([ True,  True,  True,  True])