In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   ----- ---------------------------------- 1.8/12.5 MB 15.2 MB/s eta 0:00:01
   ------------------ --------------------- 5.8/12.5 MB 17.3 MB/s eta 0:00:01
   ---------------------------- ----------- 8.9/12.5 MB 16.3 MB/s eta 0:00:01
   ---------------------------------------- 12.5/12.5 MB 17.1 MB/s  0:00:00



[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.4.6


In [ ]:
## 1. Creating arrays : 


In [4]:
list1 = [1,2, 3, 4]
print(list1)

[1, 2, 3, 4]


In [5]:
arr_list1 = np.array(list1)
print(arr_list1)

[1 2 3 4]


In [10]:
print(type(arr_list1))
print(arr_list1.ndim)

<class 'numpy.ndarray'>
1


In [11]:
list1 = [1,2,4]
list2 = [4,5,6]
arr_list1_2 = np.array([list1, list2])
print(arr_list1_2)
print(arr_list1_2.ndim)

[[1 2 4]
 [4 5 6]]
2


In [13]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
arr_list1_3 = np.array([[list1 , list2 , list3]])
print(arr_list1_3)
print(arr_list1_3.ndim)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [ ]:
## 2. numpy array attributes : 

In [15]:
arr1 = np.array([[1,2,3] , [4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [17]:
print("Shape :" , arr1.shape)
print("Size : " , arr1.size)
print("dType:" , arr1.dtype)
print("n_dim :" , arr1.ndim)

Shape : (2, 3)
Size :  6
dType: int64
n_dim : 2


In [23]:
# HW :  Create 2 array - 1D and 3D , and find it's attributes 

arr1 = np.array([1,2,3])
print(arr1)

print("Shape :" , arr1.shape)
print("Size : " , arr1.size)
print("dType:" , arr1.dtype)
print("n_dim :" , arr1.ndim)


print('-' * 50)

arr3 = np.array([[2,4,6] , [4,5,6] , [7,8,9]])
print(arr3)



print("Shape :" , arr3.shape)
print("Size : " , arr3.size)
print("dType:" , arr3.dtype)
print("n_dim :" , arr3.ndim)

[1 2 3]
Shape : (3,)
Size :  3
dType: int64
n_dim : 1
--------------------------------------------------
[[2 4 6]
 [4 5 6]
 [7 8 9]]
Shape : (3, 3)
Size :  9
dType: int64
n_dim : 2


In [ ]:
## 3. Array initialization methods : 

In [ ]:
#--> Zeros array :

In [25]:
zero_arr = np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#--> Ones array :

In [27]:
ones_arr = np.ones((1 , 4))
print(ones_arr)

[[1. 1. 1. 1.]]


In [ ]:
#--> Full array : 

In [28]:
full_arr = np.full((3,2),7)
print(full_arr)

[[7 7]
 [7 7]
 [7 7]]


In [ ]:
# Identity Matrix : 3 rows , 3 columns

In [29]:
id_arr = np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Empty array : 

In [30]:
print(np.empty(2))

[0. 0.]


In [ ]:
# evenly spaced array : 

In [32]:
print(np.arange(1, 10 ,2))

[1 3 5 7 9]


In [ ]:
# specific number of equally (spaced) values between a range : 

In [35]:
print(np.linspace(1 , 10 , 4))

[ 1.  4.  7. 10.]


In [ ]:
# random values array :   [float]

In [38]:
r_arr = np.random.rand(3,2)
print(r_arr)

[[0.79484037 0.31060892]
 [0.61778693 0.76758029]
 [0.87160928 0.24593445]]


In [ ]:
# random values array : [int]

In [39]:
rint_arr  = np.random.randint(1 , 100 , (3 ,3))
print(rint_arr)

[[15 64  7]
 [98  1  2]
 [15 62 60]]


In [ ]:
## 4. array Indexing and Slicing : 

In [40]:
a = np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [41]:
print(a[0])

1


In [42]:
print(a[-1])

9


In [43]:
#-->Slicing : 
#->array[start:stop:step]
#->stop - index , that is not included in output


In [ ]:
a = np.array([1,3,5,7,9])
print(a)

In [48]:
print(a[-3:])

[5 7 9]


In [ ]:
#--> Slicing : 2-D array

In [4]:
import numpy as np

In [5]:
arr2 = np.array([ [1,2,3] , [4,5,6] ])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [6]:
print(arr2[0])

[1 2 3]


In [7]:
print(arr2[1])

[4 5 6]


In [8]:
print(arr2[0][0])

1


In [9]:
print(arr2[0][1])

2


In [10]:
print(arr2[0][2])

3


In [11]:
print(arr2[1][0])

4


In [12]:
print(arr2[1][1])

5


In [13]:
print(arr2[1][2])

6


In [14]:
print(arr2[1])

[4 5 6]


In [15]:
print(arr2[1:])

[[4 5 6]]


In [16]:
print(arr2[:])

[[1 2 3]
 [4 5 6]]


In [17]:
print(arr2[: ,0])

[1 4]


In [18]:
print(arr2[:, 1])

[2 5]


In [19]:
print(arr2[:, 2])

[3 6]


In [ ]:
# NOTE : 

# 2D : [rows , columns]
# 3D : [layers / height , rows , columns]

In [20]:
arr3 = np.array([ [1,2,3] , [4,5,6] , [7,8,9]  ])
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
print(f"first row : {arr3[0]} , Second row : {arr3[1] }, Third row : {arr3[2]} ")

first row : [1 2 3] , Second row : [4 5 6], Third row : [7 8 9] 


In [24]:
print(f"first column : {arr3[:,0]} , Second Column : {arr3[:,1]} , Third Column : {arr3[:,2]}")

first column : [1 4 7] , Second Column : [2 5 8] , Third Column : [3 6 9]


In [ ]:
# 5.  Array Reshaping and Flattening : 

In [26]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [31]:
reshaped_arr1 = arr1.reshape((5, 1))  #-----> 5 rows  , 1 column
print(reshaped_arr1)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [34]:
reshaped2_arr1 = arr1.reshape((1, 5))  #-----> 1 rows  , 5 column
print(reshaped_arr1)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
# flatten :

In [36]:
print(reshaped2_arr1.flatten())

[1 2 3 4 5]


In [ ]:
## 6. Array Stacking and Splitting : 

In [37]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.vstack((a,b)))   # --> vertical stacking : row wise
print(np.hstack((a,b)))   # --> Horizontal stacking : column wise

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
# :--> Spiliting : 

In [38]:
c = np.array([ [1,2,3] , [4,5,6] ])
print(c)

[[1 2 3]
 [4 5 6]]


In [40]:
hsplit = np.hsplit(c , 3)   #--> horizontal split

for s in hsplit:
    print(s)

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [41]:
vsplit = np.vsplit(c, 2)  #--> vertical split 

for s in vsplit:
    print(s)

[[1 2 3]]
[[4 5 6]]


In [ ]:
# :: Mathematical Operations on Array : 

In [42]:
a = np.array([10 , 20 , 40 , -30])
print(a)

[ 10  20  40 -30]


In [43]:
print(a + 10)
print(a - 30)
print(a * 2)
print(a / 10)

[ 20  30  50 -20]
[-20 -10  10 -60]
[ 20  40  80 -60]
[ 1.  2.  4. -3.]


In [45]:
b = np.array([1,4,9])
print(b)

[1 4 9]


In [46]:
print(np.square(b))
print(np.sqrt(b))

[ 1 16 81]
[1. 2. 3.]


In [ ]:
# mathematical operations on multiple arrays : 

In [47]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a)
print(b)

[1 2 3]
[4 5 6]


In [49]:
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
# Dot Product : 

In [50]:
print(np.dot(a,b))

32


In [ ]:
# Transpose : converting rows into column and column into rows

In [52]:
t = np.array([ [1,2,3] , [4,5,6] ])
print(t)
print(t.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# stastical function : 

In [53]:
a = np.array([ [1,2,3] , [4,5,6] ])
print(a)

[[1 2 3]
 [4 5 6]]


In [54]:
print(a.sum())

21


In [56]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))

3.5
3.5
1.707825127659933
1
6


In [57]:
print(a == b )   # --> Comparing each elements

print(np.array_equal(a , b))  #--> Comparing complete array

[[False False False]
 [ True  True  True]]
False


In [ ]:
# Broadcasting : 
# -> Broadcasting is a mechanism that allows arithmetic operations to be performed on arrays of different shapes and sizes , 
# -> it eliminates the need for explicit loops or reshaping operations , making code more consize , readable and efficient. 

In [ ]:
# Ex :

In [58]:
a = np.array([1,2,3,4])
b = np.array([5])
print(a + b)

[6 7 8 9]


In [ ]:
# Ex :

In [59]:
c = np.array([ [1,2,3] , [4,5,6] ])
d = np.array([10 , 20 , 30])
print(c + d)

[[11 22 33]
 [14 25 36]]


In [ ]:
# Handelling with null value : 

In [61]:
data_1 = np.array([1 , 2 , np.nan , 4 , np.inf] )
print(data_1)

[ 1.  2. nan  4. inf]


In [62]:
print(np.isnan(data_1))

[False False  True False False]


In [63]:
print(np.nan_to_num(data_1))

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]


In [ ]:
# Save and load  arrays :

In [64]:
arr = np.array([1,0, 0 ,8])
print(arr)

np.save('my_arr_npy' ,arr)

[1 0 0 8]


In [66]:
loaded_arr = np.load('my_arr_npy.npy')
print(loaded_arr)

[1 0 0 8]


In [ ]:
# :: Homework :

In [ ]:
# 1. Create 5 x 5 matrix with values from  1 to 25. 
# -> Extract last row , first column , mub